# Advertise Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/Advertise

#=====================#
#   Announce Config   #
#=====================#
# Prefix of advertise message
Prefix: "&c[Ad]&f "
# Announce interval in Minutes
AnnounceInterval: 5
# Use hide permission (advertise.hide)
UseHidePermission: false

#==================#
#   Limit Config   #
#==================#
MaxDays: 7

#==================#
#   Vault Config   #
#==================#
# Use Vauld plugin
UseVault: false
CostPerDay: 1000

#==================#
#   MySQL Config   #
#==================#
MySQL:
  Server:
    Address: localhost
    Port: 3306
  Database:
    Name: DatabaseName
    User_Name: UserName
    User_Password: UserPassword
    TablePrefix: ad_

#==================#
#   Debug Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
ConfigVersion: 1