# Advertise Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/Advertise

#==================#
#   Debug Config   #
#==================#
UseVault: false
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
ConfigVersion: 1